ecommerce/config/routes.rb
Rails.application.routes.draw do
 
  
  resources :products
  # resources :carts
  resources :coupons
  resources :categories
  resources :brands
  resources :products 
  resources :carts
  resources :stores

  
  # get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  
  
  
  
  
  
  
  
  
  
  
  resources :orders 
  resources :order_products 
  
  resources :carts  do
    end


end

ecommerce/app/models/coupon.rb
class Coupon < ApplicationRecord
    has_and_belongs_to_many :users
    has_many :products
    validates :title , presence:true, on: :create
    validates :expiring_type , presence:true, on: :create
    validates :discount_Type , presence:true, on: :create
    validates :discount_value , presence:true, on: :create





    def is_valide_coupon
        if self.expiring_type == "expiring_date"
            return self.expiring_date >= DateTime.now
        elsif self.expiring_type=="usage_num"
            return self.usage_num.to_i > self.current_usage.to_i
        else 
            return (self.expiring_date >= DateTime.now) && (self.usage_num.to_i > self.current_usage.to_i)
        end        
    end

    def coupon_info
        coupinfo=self.discount_Type + " with value: " +self.discount_value.to_s
        coupinfo
    end  
    

   def get_products
    @products=Product.all
   end

end

ecommerce/app/controllers/coupons_controller.rb
class CouponsController < InheritedResources::Base
  load_and_authorize_resource

  def index
    @coupons=Coupon.all
    @products=Product.all 
    authorize! :crud, @coupon       
    end
    def new
      @coupon =Coupon.new
      @products=Product.all 
      authorize! :crud, @coupon              
    end
  
    def create
      @products=Product.all          
      @coupon = Coupon.new(product_params)
      if @coupon.save
        redirect_to @coupon
      else
          render 'new'
      end
      authorize! :crud, @coupon       
    end
  
    def edit
      @coupon = Coupon.find(params[:id])
      @products=Product.all 
      authorize! :crud, @coupon              
    end


  private

    def coupon_params
      params.require(:coupon).permit(:discount_Type, :discount_value, :usage_num,:expiring_date,:expiring_type, :title)
    end

end

ecommerce/app/helpers/coupons_helper.rb
module CouponsHelper
end

ecommerce/app/views/coupons/_form.html.erb
<%= form_with(model: coupon, local: true) do |form| %>
  <% if coupon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(coupon.errors.count, "error") %> prohibited this coupon from being saved:</h2>

      <ul>
      <% coupon.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field(:title) %>
  </div>

  <div class="field">
    <%= form.label :expiring_date %>
    <%= form.datetime_select :expiring_date %>
  </div>

  <div class="field">
    <%= form.label :discount_value %>
    <%= form.number_field :discount_value %>
  </div>

  <div class="field">
    <%= form.label :discount_Type %>
    <%= form.select :discount_Type, options_for_select(["Fixed", "Percentage"]), :class => 'genForm_dropBox' %>


    </div>

  <div class="field">
    <%= form.label :usage_num %>
    <%= form.number_field :usage_num %>
  </div>
  <div class="field">
    <%= form.label :expiring_type %>
    <%= form.select :expiring_type, options_for_select(["Usage_num", "Expiring_date","Both"]), :class => 'genForm_dropBox' %>
  </div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ecommerce/app/views/coupons/edit.html.erb
<h1>Editing Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Show', @coupon %> |
<%= link_to 'Back', coupons_path %>

ecommerce/app/views/coupons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Coupons</h1>

<table>
  <thead>
    <tr>
      <th>Coupon Title</th>
      <th>Expiring Date</th>
      <th>Discount Value</th>
      <th>Discount Type</th>
      <th>Usage Num</th>
      <th>Expiring Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @coupons.each do |coupon| %>
      <tr>
        <td><%= coupon.title %></td>
        <td><%= coupon.expiring_date %></td>
        <td><%= coupon.discount_value %></td>
        <td><%= coupon.discount_Type %></td>
        <td><%= coupon.usage_num %></td>
        <td><%= coupon.expiring_type %></td>
        <td><%= link_to 'Show', coupon %></td>
        <td><%= link_to 'Edit', edit_coupon_path(coupon) %></td>
        <td><%= link_to 'Destroy', coupon, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Coupon', new_coupon_path %>

ecommerce/app/views/coupons/new.html.erb
<h1>New Coupon</h1>

<%= render 'form', coupon: @coupon %>

<%= link_to 'Back', coupons_path %>

ecommerce/app/views/coupons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Coupon Title:</strong>
  <%= @coupon.title %>
</p>

<p>
  <strong>Expiring_date:</strong>
  <%= @coupon.expiring_date %>
</p>

<p>
  <strong>Discount Value:</strong>
  <%= @coupon.discount_value %>
</p>

<p>
  <strong>Discount Type:</strong>
  <%= @coupon.discount_Type %>
</p>

<p>
  <strong>Usage Num:</strong>
  <%= @coupon.usage_num %>
</p>

<p>
  <strong>Expiring Type:</strong>
  <%= @coupon.expiring_type %>
</p>

<%= link_to 'Edit', edit_coupon_path(@coupon) %> |
<%= link_to 'Back', coupons_path %>