ecommerce/config/routes.rb
Rails.application.routes.draw do
 
  
  resources :products
  # resources :carts
  resources :coupons
  resources :categories
  resources :brands
  resources :products 
  resources :carts
  resources :stores

  
  # get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  
  
  
  
  
  
  
  
  
  
  
  resources :orders 
  resources :order_products 
  
  resources :carts  do
    end


end

ecommerce/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_products
  has_many :products ,:through => :order_products

  validates :address , presence:true,:length => { :minimum => 8,:maximum   => 20, } , on: :create
  validates :credit_cart, presence:true, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." },:length => { :is => 10, } , on: :create
  validates :phone, presence:true, format: { with: /\A\d+\z/, message: "Integer only. No sign allowed." },:length => { :is => 12, } , on: :create

end

ecommerce/app/controllers/orders_controller.rb
class OrdersController < InheritedResources::Base
  # before_action :validates, only: [:new,:create]

  before_action :authenticate_user!

   def show
       @order = Order.find(params[:id])
   end
  def new
      @order = Order.new
    end
   def index
      @orders = current_user.orders
   end

   def create
    # flash.now[:error] = "Your cart is empty   ."  
    @order = Order.new(order_params)
    @order.user=current_user
    

    carts =current_user.carts
    validate =0
    errors=[]
    if carts.count == 0
      errors.push("cart is empty")
    end
       
    carts.each do|item|
      if item.quantity.to_i > item.product.quantity_in_stock.to_i
          errors.push("product #{item.product.title} not available in stock with Quqntity #{item.quantity} " )
      end
    end
    @order.valid?
     if errors.count == 0
         @order.status="pending"
         @order.total_price = @order.actual_price = 0 
         if @order.save 
            total_price = 0
            actual_price = 0 
            carts.each do|item|
              #######################
                      @order_product=OrderProduct.new
                      @order_product.order_id = @order.id
                      @order_product.product = item.product
                      @order_product.quantity =item.quantity
                      @order_product.unit_price =item.unit_price
                      @order_product.status="pending"
                      @order_product.calculate_actual_price
                      @order_product.save
                      ############ after save order _product 
                      total_price += @order_product.quantity * @order_product.unit_price
                      actual_price += @order_product.actual_price.to_i
              end
              @order.actual_price = actual_price
              @order.total_price = total_price
              @order.save
              current_user.carts.delete_all
              redirect_to "/orders"
            else
              render 'new'
            end
      
      else 
        flash[:error] = "Your cart is empty or in valid check your cart !!!  ."  
        render 'new'             
      end

    end
  

  private

    def order_params
      params.require(:order).permit(:address,:credit_cart,:phone)
      
    end

end

ecommerce/app/helpers/orders_helper.rb
module OrdersHelper
end

ecommerce/app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :credit_cart %>
    <%= form.text_field :credit_cart %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

ecommerce/app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

ecommerce/app/views/orders/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<h2 style="color:#4a4a96;">Orders</h2>
<br>

  <table class="table">
  <thead>
    <tr>
      <th>User</th>
      <th>Total price</th>
      <th>Actual price</th>
      <th>Status</th>
      <th>Address</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.user.name %></td>
        <td><%= order.total_price %></td>
        <td><%= order.actual_price %></td>
        <td><%= order.status %></td>
        <td><%= order.address %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_order_path %>
</div>

ecommerce/app/views/orders/new.html.erb
<div class="container" style="margin-top: 25px; margin: auto;">
<h2 style="color:#4a4a96; margin-top:20px;" class=" text-center">New Order</h2>
<br>
<div style="width:50%;">
<%= render 'form', order: @order %>
</div>

<div class="alert alert-error">
      <% flash.each do |key, value| %>
        <div class="alert alert-warning" role="alert"><%= value %></div>
      <% end %>
      <%= yield %>
    </div>
<br><br>
<%= link_to 'Back', orders_path %>
</div>

ecommerce/app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order.user.id %>
</p>

<p>
  <strong>Total price:</strong>
  <%= @order.total_price %>
</p>


<p>
  <strong>Actual price:</strong>
  <%= @order.actual_price %>
</p>

<p>
  <strong>Status:</strong>
  <%= @order.status %>
</p>

<p>
  <strong>Address:</strong>
  <%= @order.address %>
</p>

<%= @order.order_products %> |                <%# loop to render all order_item_in_product %>


<%= link_to 'Show order details', order_products_path(@order.id) %> |
<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
<%= @ii %>
<%= @order_id %>