ecommerce/config/routes.rb
Rails.application.routes.draw do
 
  
  resources :products
  # resources :carts
  resources :coupons
  resources :categories
  resources :brands
  resources :products 
  resources :carts
  resources :stores

  
  # get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  
  
  
  
  
  
  
  
  
  
  
  resources :orders 
  resources :order_products 
  
  resources :carts  do
    end


end

ecommerce/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :brand
  belongs_to :user
  belongs_to :coupon, optional: true
  has_one_attached :image
  has_many :order_products
  has_many :orders, :through =>:order_products
  has_many :carts
  has_many :users, :through =>:carts

  
  validates :title , presence:true, on: :create
  validates :title , presence:true, on: :update
  validates :price , presence:true, on: :create
  validates :price , presence:true, on: :update
  validates :quantity_in_stock , presence:true, on: :create
  validates :quantity_in_stock , presence:true, on: :update
  validates :description , presence:true,:length => { :minimum => 4,:maximum   => 100, } , on: :create
  validates :description , presence:true,:length => { :minimum => 4,:maximum   => 100, } , on: :update

  def product_category
    category.name
  end

  def product_brand
    brand.name
  end
  def product_seller
    user.name
  end
  def product_coupon
   if coupon.present?
    coupon.title
   else
    "No coupon covers this product"
   end
  end

  





  def self.search_by(search_term)
    # @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}").where("category_id LIKE ?","#{filter_term}")

    @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}")
  end
  def self.filter(filter_term,search_term)
    @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}").where("category_id LIKE ?","#{filter_term}")
  end
  def self.filterb(filter_brand,search_term)
    @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}").where("brand_id LIKE ?","#{filter_brand}")

    # where("brand_id LIKE ?","#{filter_brand}")
  end
  def self.filters(filter_seller,search_term)
    @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}").where("user_id LIKE ?","#{filter_seller}")

    # where("brand_id LIKE ?","#{filter_brand}")
  end
  def self.filterp(price,tprice,search_term)
    @Product=Product.where("LOWER(title) LIKE :search_term OR LOWER(description) LIKE :search_term ",search_term: "%#{search_term.downcase}").where("price > ? AND price < ? " , "#{price.to_i}","#{tprice.to_i}")
  end
  # def get_coupon
  #   # product = Product.find(id:product_id)
  #    self.coupon
  # end
end

ecommerce/app/controllers/products_controller.rb
class ProductsController < InheritedResources::Base
  before_action :authenticate_user!, except: [:index,:show]
    # include CanCan::ControllerAdditions
  load_and_authorize_resource
  skip_authorize_resource :only => [:index, :show]
  def index
    if user_signed_in?
      if current_user.is_seller?
       @products=Product.where(user_id:current_user.id)
     else
        @products=Product.all
      end
    else 
      @products=Product.all
    end
    @brand=Brand.all
    @category=Category.all    
    @user=User.all
    # =============================
    # if params[:search] and params[:product][:category_id]=nil
    if params[:search]
      @search_term=params[:search]
      @products=Product.search_by(@search_term)
      @brand=Brand.all
      @user=User.all
      @category=Category.all
      # @search_term=params[:search]
      if params[:product][:category_id] !='' and (params[:product][:brand_id] =='' or params[:product][:brand_id] !='')  and (params[:product][:user_id] =='' or params[:product][:user_id] !='')  and (params[:fromprice][:price] =='' or params[:fromprice][:price] !='') 
        @filter_brand=params[:product][:brand_id]
        @filter_term=params[:product][:category_id]
        @search_term=params[:search]
        @tprice =params[:toprice][:tprice]
        @price =params[:fromprice][:price]
        # @p=@products.filter(@search_term)
        @products=Product.filter(@filter_term,@search_term)
        @brand=Brand.all
        @user=User.all

        @category=Category.all
      elsif params[:product][:brand_id] !='' and (params[:product][:category_id] =='' or params[:product][:category_id] !='') 
        @filter_brand=params[:product][:brand_id]

        @search_term=params[:search]

        @products=Product.filterb(@filter_brand,@search_term)
        @user=User.all

        @brand=Brand.all
        @category=Category.all


      elsif params[:toprice][:tprice] !='' and params[:fromprice][:price] !=''  and   (params[:product][:brand_id] !='' or params[:product][:brand_id] =='' ) and (params[:product][:category_id] !='' or params[:product][:category_id] =='' )  
        # @filter_seller=params[:product][:user_id]
        @search_term=params[:search]
        @tprice =params[:toprice][:tprice]
        @price =params[:fromprice][:price]
       
        @products=Product.filterp(@price,@tprice,@search_term,)
        @seller=User.all
        @brand=Brand.all
        @category=Category.all
         

      elsif params[:product][:user_id] !='' and (params[:product][:brand_id] =='' or params[:product][:brand_id] !='') and (params[:product][:category_id] =='' or params[:product][:category_id] !='') 
        @filter_seller=params[:product][:user_id]
        
        @search_term=params[:search]

        @products=Product.filters(@filter_seller,@search_term)
        @user=User.all

        @brand=Brand.all
        @category=Category.all

      elsif params[:product][:category_id] =='' and params[:product][:brand_id] =='' and params[:product][:user_id] =='' 
        @products=Product.search_by(@search_term)
        @brand=Brand.all
        @category=Category.all
        @user=User.all
        

 
      end


    end

  end 
  

  def new
    @product =Product.new
    @categories = Category.all
    @brands = Brand.all
    @coupons=Coupon.all
    #  @stores = Store.all 
    #  @users = User.where(id:current_user.id)
    authorize! :crud, @product
  end

  def create
    @brands = Brand.all
    @categories = Category.all
    @coupons=Coupon.all

    @product = Product.new(product_params)
    puts "=============== #{product_params}==================="
    @product.user_id = current_user.id
    # @product.coupon_id = current_user.id
    if @product.save
      redirect_to products_path
    else
        render 'new'
    end
    authorize! :crud, @product
  end

  def edit
    @coupons=Coupon.all

    @product = Product.find(params[:id])
    @categories = Category.all
    @brands = Brand.all
    @coupons=Coupon.all
    # @stores = Store.all 
    @users = User.where(id:current_user.id)
    @product.user_id = current_user.id
    authorize! :crud, @product
  end

  def update
    @product = Product.find(params[:id])
    @categories = Category.all
    @brands = Brand.all
    @coupons=Coupon.all
    if @product.update(product_params)
      redirect_to @product
    else
      render 'edit'
    end
    authorize! :crud, @product
  end

  private

    def product_params
      params.require(:product).permit(:title, :image, :price, :quantity_in_stock, :description, :category_id, :brand_id, :coupon_id)
    end

end

ecommerce/app/helpers/products_helper.rb
module ProductsHelper
end

ecommerce/app/views/products/_form.html.erb
<div class="container">
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
    <%# <%= form.text_area :image %> 
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :quantity_in_stock %>
    <%= form.number_field :quantity_in_stock %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :category_id %>
    <%= form.collection_select(:category_id,@categories,:id,:name,{ :prompt => 'Select a Category', :selected => @product.category_id }, { class: 'form-control' } )%>
  </div>

  <div class="field">
    <%= form.label :brand_id %>
    <%= form.collection_select(:brand_id,@brands,:id,:name,{ :prompt => 'Select a Brand', :selected => @product.brand_id }, { class: 'form-control' } )%>
  </div>

  <%# <div class="field">
    <%= form.label :user_id %>
    <%# <%= form.text_field :user_id %> 
  <%# </div> %> 

  <div class="field">
    <%= form.label :coupon_id  %>
    <%= form.collection_select(:coupon_id ,@coupons,:id,:coupon_info ,{ :prompt => 'Select a Coupon', :selected => @product.coupon_id  }, { class: 'form-control' } )%>
  </div>

  <%# <div class="field">
    <%= form.label :coupon_id %>
    <%# <%= form.text_field :coupon_id %> 
  <%# </div> %> 
 <br>

  <div class="actions btn btn-primary">
    <%= form.submit %>
  </div>
<% end %>
</div>

ecommerce/app/views/products/edit.html.erb
<div class="container" style="margin-top: 25px; margin: auto;">
<h2 style="color:#4a4a96; margin-top:20px;" class=" text-center">Editing Product</h2>
<br>
<div style="width:50%;">


<%= render 'form', product: @product %>
</div>
<br>
<br>
<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>
</div>

ecommerce/app/views/products/index.html.erb
<div class="container" style="margin-top: 25px; margin: auto;">
<p id="notice"><%= notice %></p>
<%= @order %>

<h1>Products</h1>
<% if user_signed_in? %>
  <p>search with title or description:<p>
  <%= form_for "",url: products_path ,role:"search", method: :get do%>
    <%= text_field_tag :search ,@search_term, placeholder: "search..." %>
    <%= form_tag products_path ,:method => 'get' do%>
      <%= collection_select :product, :brand_id, @brand, :id,:name, prompt: true %>
      <%= collection_select :product, :user_id, @user, :id,:name, prompt: true %>

      <%= collection_select :product, :category_id, @category, :id,:name, prompt: true %>
  
      <br>
      <span>Price from </span> <%= number_field 'fromprice','price' %>
      <span>Price to </span><%= number_field 'toprice','tprice' %>
      <%= submit_tag "select product" %>
    <% end %> 
  <% end %>
<% end %>
  <div class="row products_row" style="margin-top: 10px; margin: auto;">

  <% if (@products) %>
    <% if (@products.empty?) %>
      <p>No product found.</p>
      <%= link_to 'New Product', new_product_path %>
  <% else %>
      <% @products.each do |product| %>
					<!-- Product -->
					<div class="card" style="width: 18rem; margin-top: 45px; margin-right: 3%;">
            <% if product.image.attached? %>
              <%= image_tag product.image  , class:"card-img-top" , style:"height:90%"%>
            <% else %>
              <%= image_tag 'app/assets/images/myavatar.png' %>
            <% end %>
            <div class="card-body" style="height:40%" >
              <p class="card-title" style="float:left"><%= link_to product.title, product  %></p>
              <p class="card-text" style="float:right;margin-left:10%"> $ <%= product.price %></p>
              <div style="clear:both"></div>
              <%= link_to 'Add To Cart', product , class:"btn btn-outline-info" %>
              <% if user_signed_in? %>
                <% if current_user.is_seller? %>
                  <%= link_to 'Delete', product, method: :delete, data: { confirm: 'Are you sure?' } , class:"btn btn-outline-danger glyphicon glyphicon-remove", style:"margin-left:20%;" %>
                <% end %>
              <% end %>
            </div>
          </div>
    <% end %>  
    <% end %>
  <% end %>
  </div>
  <br><br>
  <!-- Only Sellers can see this link -->
  <% if user_signed_in? %>
    <% if current_user.is_seller? %>
      <%= link_to 'New Product', new_product_path ,class:"btn btn-success" %>
    <% end %>
  <% end %>
  

  </div>

ecommerce/app/views/products/new.html.erb
<div class="container" style="margin-top: 25px; margin: auto;">
<h2 style="color:#4a4a96; margin-top:20px;" class=" text-center">New Product</h2>
<br>
<div style="width:50%;">
<%= render 'form', product: @product %>
</div>
<br>
<br>
<%= link_to 'Back', products_path , class:"btn btn-warning" %>
</div>

ecommerce/app/views/products/show.html.erb
<div class="container" style="margin-top:100px">
	<div class="row">
		<!-- Product Image -->
		<div class="col-lg-6">
			<div style="width:100%">
				<% if @product.image.attached? %>
            <%= image_tag @product.image ,style:"width:100%;border-radius:30px;"%>
        <% else %>
            <%= image_tag 'app/assets/images/myavatar.png' %>
        <% end %>
							
			</div>
		</div>
    <!-- Product Info -->
		<div class="col-lg-6 text-center">
			<div style="margin-left:20px;">
				<h2  style="color:#4a4a96;"><%= @product.title %></h2>
        <br>
        <h4 style="color:#4a4a96;">Description: <%= @product.description %></h4>
        <h4 style="color:#4a4a96;">Price: $ <%= @product.price %></h4>
        <h4 style="color:#4a4a96;">Brand: <%= @product.product_brand %></h4>
        <h4 style="color:#4a4a96;">Category: <%= @product.product_category %></h4>
        <h4 style="color:#4a4a96;">Coupon: <%= @product.product_coupon %></h4>
        <h4 style="color:#4a4a96;">Seller: <%= @product.product_seller %></h4>
        <h4 style="color:#4a4a96;"> Available Quantity: <%= @product.quantity_in_stock %></h4>
        <br>
       <br>
						<%= button_to "Add to cart", carts_path(:product_id => @product.id) ,class:"btn btn-success" %>	
            
            <%= link_to 'Back', products_path  ,class:"btn btn-warning"%>
            
            <br><br>

            

 <%= link_to 'Edit', edit_product_path(@product),class:"btn btn-outline-primary" %>
				</div>
			</div>

		</div>
	</div>