ecommerce/config/routes.rb
Rails.application.routes.draw do
 
  
  resources :products
  # resources :carts
  resources :coupons
  resources :categories
  resources :brands
  resources :products 
  resources :carts
  resources :stores

  
  # get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root 'products#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  

  
  
  
  
  
  
  
  
  
  
  
  resources :orders 
  resources :order_products 
  
  resources :carts  do
    end


end

ecommerce/app/models/brand.rb
class Brand < ApplicationRecord
    has_many :products, dependent: :destroy
    validates :name, presence: true, uniqueness: true

end

ecommerce/app/controllers/brands_controller.rb
class BrandsController < InheritedResources::Base
  load_and_authorize_resource

  private

    def brand_params
      params.require(:brand).permit(:name)
    end

end

ecommerce/app/helpers/brands_helper.rb
module BrandsHelper
end

ecommerce/app/views/brands/_form.html.erb
<div class="container">
<br>
<%= form_with(model: brand, local: true) do |form| %>
  <% if brand.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(brand.errors.count, "error") %> prohibited this brand from being saved:</h2>

      <ul>
      <% brand.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</div>

ecommerce/app/views/brands/edit.html.erb
<h1>Editing Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Show', @brand %> |
<%= link_to 'Back', brands_path %>

ecommerce/app/views/brands/index.html.erb
<div class="container">
<br>
<p id="notice"><%= notice %></p>

<h1>Brands</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @brands.each do |brand| %>
      <tr>
        <td><%= brand.name %></td>
        <td><%= link_to 'Show', brand %></td>
        <td><%= link_to 'Edit', edit_brand_path(brand) %></td>
        <td><%= link_to 'Destroy', brand, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Brand', new_brand_path %>
</div>

ecommerce/app/views/brands/new.html.erb
<h1>New Brand</h1>

<%= render 'form', brand: @brand %>

<%= link_to 'Back', brands_path %>

ecommerce/app/views/brands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @brand.name %>
</p>

<%= link_to 'Edit', edit_brand_path(@brand) %> |
<%= link_to 'Back', brands_path %>